# Generated by Django 3.0.3 on 2020-06-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='usre',
            new_name='user',
        ),
    ]
